apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: job-api
  template:
    metadata:
      labels:
        app: job-api
    spec:
      containers:
      - name: job-api
        image: mycontainerregistrykode.azurecr.io/job-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: azure-keyvault-secrets  # Nombre del Secret
              key: DATABASE_URL             # Clave en el Secret
      imagePullSecrets:
      - name: acr-credentials  # Secret para autenticarse con ACR