apiVersion: v1
kind: Service
metadata:
  name: job-api-service
spec:
  type: LoadBalancer  # Expone el servicio externamente
  ports:
    - port: 80        # Puerto externo
      targetPort: 5000 # Puerto interno del contenedor
  selector:
    app: job-api      # Selecciona los pods con esta etiqueta